/**
 * Export Utilities
 * Functions to export analysis results in various formats
 */

import { AnalysisResult } from '@/types';

/**
 * Export analysis as JSON
 */
export function exportAsJSON(analysis: AnalysisResult): void {
  const json = JSON.stringify(analysis, null, 2);
  downloadFile(json, 'analysis-result.json', 'application/json');
}

/**
 * Export analysis as Markdown
 */
export function exportAsMarkdown(analysis: AnalysisResult): void {
  const markdown = generateMarkdown(analysis);
  downloadFile(markdown, 'analysis-result.md', 'text/markdown');
}

/**
 * Export analysis as PDF (generates HTML for print)
 */
export function exportAsPDF(analysis: AnalysisResult): void {
  const html = generateHTML(analysis);
  
  // Create a new window for printing
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    
    // Trigger print dialog
    setTimeout(() => {
      printWindow.print();
    }, 250);
  }
}

/**
 * Generate Markdown content
 */
function generateMarkdown(analysis: AnalysisResult): string {
  const { analysis: codeAnalysis, explanation, onboarding, documentation } = analysis;
  
  let markdown = `# Codebase Analysis Report

**Project:** ${codeAnalysis.metadata.name}
**Date:** ${new Date(codeAnalysis.timestamp).toLocaleDateString()}
**Architecture:** ${codeAnalysis.architecture.type}

---

## Summary

${codeAnalysis.summary}

## Project Statistics

- **Total Files:** ${codeAnalysis.metadata.totalFiles}
- **Total Lines:** ${codeAnalysis.metadata.totalLines.toLocaleString()}
- **Complexity Score:** ${codeAnalysis.complexityScore}/100
- **Languages:** ${codeAnalysis.metadata.languages.map(l => l.language).join(', ')}
- **Frameworks:** ${codeAnalysis.metadata.frameworks.join(', ')}

## Language Distribution

${codeAnalysis.metadata.languages.map(lang => 
  `- **${lang.language}:** ${lang.percentage.toFixed(1)}% (${lang.files} files)`
).join('\n')}

## Architecture

**Pattern:** ${codeAnalysis.architecture.type}

**Confidence:** ${codeAnalysis.architecture.confidence}%

**Description:** ${codeAnalysis.architecture.description}

**Components:**
${codeAnalysis.architecture.components.map(c => `- ${c}`).join('\n')}

## Key Files

${codeAnalysis.keyFiles.map(file => 
  `### ${file.path}
- **Importance:** ${file.importance}
- **Lines:** ${file.linesOfCode}
- **Reason:** ${file.reason}
`).join('\n')}

## Risks and Issues

${codeAnalysis.risks.length > 0 ? codeAnalysis.risks.map(risk => 
  `### ${risk.severity.toUpperCase()}: ${risk.category}
${risk.description}
${risk.suggestion ? `\n**Suggestion:** ${risk.suggestion}` : ''}
${risk.location ? `\n**Location:** ${risk.location}` : ''}
`).join('\n') : 'No significant risks identified.'}
`;

  // Add explanation if available
  if (explanation) {
    markdown += `\n## Explanation (${explanation.level})

${explanation.details}

${explanation.nextSteps && explanation.nextSteps.length > 0 ? `
### Next Steps
${explanation.nextSteps.map((step, i) => `${i + 1}. ${step}`).join('\n')}
` : ''}
`;
  }

  // Add onboarding guide if available
  if (onboarding) {
    markdown += `\n## Onboarding Guide

### Overview
${onboarding.overview}

### Getting Started
${onboarding.gettingStarted.map((step, i) => `${i + 1}. ${step}`).join('\n')}

### Setup Instructions
${onboarding.setupInstructions.map((step, i) => `${i + 1}. ${step}`).join('\n')}

### Common Pitfalls
${onboarding.commonPitfalls.map(pitfall => `- ${pitfall}`).join('\n')}

### Suggested Tasks
${onboarding.suggestedTasks.map(task => `- ${task}`).join('\n')}
`;
  }

  // Add documentation if available
  if (documentation) {
    markdown += `\n## Generated Documentation

${documentation.readme || 'No README generated'}
`;
  }

  markdown += `\n---

*Generated by Codebase CoPilot*
*© 2026 Codebase CoPilot. All Rights Reserved. A Brand of COBRA AI Systems.*
`;

  return markdown;
}

/**
 * Generate HTML content for PDF export
 */
function generateHTML(analysis: AnalysisResult): string {
  const markdown = generateMarkdown(analysis);
  
  // Convert markdown to HTML (simple conversion)
  const html = markdown
    .replace(/^# (.*$)/gim, '<h1>$1</h1>')
    .replace(/^## (.*$)/gim, '<h2>$1</h2>')
    .replace(/^### (.*$)/gim, '<h3>$1</h3>')
    .replace(/^\*\*(.*)\*\*/gim, '<strong>$1</strong>')
    .replace(/^\- (.*$)/gim, '<li>$1</li>')
    .replace(/^\d+\. (.*$)/gim, '<li>$1</li>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br>');

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Codebase Analysis Report</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
    }
    h1 {
      color: #0f62fe;
      border-bottom: 3px solid #0f62fe;
      padding-bottom: 10px;
    }
    h2 {
      color: #0f62fe;
      margin-top: 30px;
      border-bottom: 2px solid #e0e0e0;
      padding-bottom: 5px;
    }
    h3 {
      color: #333;
      margin-top: 20px;
    }
    strong {
      color: #000;
    }
    li {
      margin: 5px 0;
    }
    code {
      background: #f4f4f4;
      padding: 2px 6px;
      border-radius: 3px;
      font-family: 'Courier New', monospace;
    }
    @media print {
      body {
        padding: 0;
      }
      h1 {
        page-break-before: always;
      }
      h1:first-child {
        page-break-before: avoid;
      }
    }
  </style>
</head>
<body>
  ${html}
</body>
</html>
`;
}

/**
 * Download file helper
 */
function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Export documentation as separate files
 */
export function exportDocumentation(documentation: any): void {
  if (documentation.readme) {
    downloadFile(documentation.readme, 'README.md', 'text/markdown');
  }
  if (documentation.apiDocs) {
    downloadFile(documentation.apiDocs, 'API.md', 'text/markdown');
  }
  if (documentation.architectureDocs) {
    downloadFile(documentation.architectureDocs, 'ARCHITECTURE.md', 'text/markdown');
  }
  if (documentation.setupGuide) {
    downloadFile(documentation.setupGuide, 'SETUP.md', 'text/markdown');
  }
  if (documentation.contributingGuide) {
    downloadFile(documentation.contributingGuide, 'CONTRIBUTING.md', 'text/markdown');
  }
}

/**
 * Export test suite
 */
export function exportTests(tests: any): void {
  tests.tests.forEach((test: any) => {
    downloadFile(test.testCode, test.filePath.split('/').pop() || 'test.js', 'text/plain');
  });
}

/**
 * Export refactoring suggestions as CSV
 */
export function exportRefactoringsAsCSV(refactorings: any[]): void {
  const headers = ['Type', 'Severity', 'Location', 'Issue', 'Suggestion', 'Impact'];
  const rows = refactorings.map(r => [
    r.type,
    r.severity,
    r.location,
    `"${r.issue.replace(/"/g, '""')}"`,
    `"${r.suggestion.replace(/"/g, '""')}"`,
    `"${r.impact.replace(/"/g, '""')}"`,
  ]);
  
  const csv = [headers, ...rows].map(row => row.join(',')).join('\n');
  downloadFile(csv, 'refactoring-suggestions.csv', 'text/csv');
}

// Made with Bob
